"""Multi-language internationalization support."""

from __future__ import annotations

LOCALE_MAP: dict[str, dict[str, str]] = {
    "en": {
        "scan_header": "## Security Scan Results",
        "scan_summary": "Scanned {files} files, found {issues} potential issues",
        "review_header": "## PR Review",
        "review_summary": "Review complete — {comments} comments",
        "test_header": "## Test Report",
        "test_summary": "{passed} passed, {failed} failed, {skipped} skipped, {errors} errors",
        "severity_critical": "CRITICAL",
        "severity_high": "HIGH",
        "severity_medium": "MEDIUM",
        "severity_low": "LOW",
        "footer": "Generated by Multi-Model Agent",
    },
    "zh": {
        "scan_header": "## 安全扫描结果",
        "scan_summary": "已扫描 {files} 个文件，发现 {issues} 个潜在问题",
        "review_header": "## 代码审查",
        "review_summary": "审查完成 — {comments} 条评论",
        "test_header": "## 测试报告",
        "test_summary": "{passed} 通过, {failed} 失败, {skipped} 跳过, {errors} 错误",
        "severity_critical": "严重",
        "severity_high": "高",
        "severity_medium": "中",
        "severity_low": "低",
        "footer": "由 Multi-Model Agent 生成",
    },
    "ja": {
        "scan_header": "## セキュリティスキャン結果",
        "scan_summary": "{files} ファイルをスキャンし、{issues} 件の潜在的問題を検出",
        "review_header": "## PR レビュー",
        "review_summary": "レビュー完了 — {comments} 件のコメント",
        "test_header": "## テストレポート",
        "test_summary": "{passed} 成功, {failed} 失敗, {skipped} スキップ, {errors} エラー",
        "severity_critical": "重大",
        "severity_high": "高",
        "severity_medium": "中",
        "severity_low": "低",
        "footer": "Multi-Model Agent により生成",
    },
    "ko": {
        "scan_header": "## 보안 스캔 결과",
        "scan_summary": "{files}개 파일 스캔, {issues}개 잠재적 문제 발견",
        "review_header": "## PR 리뷰",
        "review_summary": "리뷰 완료 — {comments}개 코멘트",
        "test_header": "## 테스트 보고서",
        "test_summary": "{passed} 통과, {failed} 실패, {skipped} 건너뜀, {errors} 오류",
        "severity_critical": "심각",
        "severity_high": "높음",
        "severity_medium": "중간",
        "severity_low": "낮음",
        "footer": "Multi-Model Agent 생성",
    },
}


def get_strings(lang: str) -> dict[str, str]:
    """Get locale strings for a given language, falling back to English."""
    return LOCALE_MAP.get(lang, LOCALE_MAP["en"])


def translate(text: str, lang: str, **kwargs: str) -> str:
    """Look up a localized string and format with kwargs."""
    strings = get_strings(lang)
    template = strings.get(text, text)
    return template.format(**kwargs)
